env:
  browser: true
  es6: true
  node: true
extends:
  - google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: 'babel-eslint'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}
